syntax = "proto3";

package gamepb.careerpb;

service CareerService {
    rpc CareerInfoGet(CareerInfoGetRequest) returns (CareerInfoGetReply);
}

message CareerInfoGetRequest {
    int64 gid = 1;
}

message CareerHarvestItem {
    int64 fruit_id = 1;
    int64 harvest_count = 2;
}

message CareerInfoGetReply {
    repeated CareerHarvestItem harvest_items = 1;
    int64 total_harvest_count = 2;
    int64 total_steal_count = 3;
    string name = 4;
    string avatar_url = 5;
    int64 level = 9;
    int64 exp = 10;
    int64 gid = 11;
    int32 platform = 13;
    string open_id = 15;
}
